version: "3.8"

services:
  app:
    build:
      context: ./foo
      # target: final # используем финальный stage из многоступенчатой сборки
    ports:
      - "5000:5000"
    environment:
      - APP_ENV=production
      - PORT=5000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=mydb
      - DB_USER=user
      - DB_PASSWORD=password
      - REDIS_URL=redis:6379
    restart: unless-stopped
