version: "3.8"

services:
  backend:
    build:
      context: ./foo
      # target: final # используем финальный stage из многоступенчатой сборки
    ports:
      - "5000:5000"
    environment:
      - APP_ENV=production
      - PORT=5000
    restart: unless-stopped
    networks:
      - app-network
  frontend:
    volumes:
      - ./frontend/dist:/app/dist
    build:
      context: ./frontend
    networks:
      - app-network
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
