version: "3.8"

services:
  backend:
    build:
      context: ./foo
      # target: final # используем финальный stage из многоступенчатой сборки
    ports:
      - "5000:5000"
    environment:
      - APP_ENV=production
      - PORT=5000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=mydb
      - DB_USER=user
      - DB_PASSWORD=password
      - REDIS_URL=redis:6379
    restart: unless-stopped
    networks:
      - app-network
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html
    depends_on:
      # - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
