version: "3.8"

services:
  backend:
    build:
      context: ./foo
      # target: final # используем финальный stage из многоступенчатой сборки
    ports:
      - "5000:5000"
    environment:
      - APP_ENV=production
      - PORT=5000
    restart: unless-stopped
    volumes:
      - ./:/
    networks:
      - app-network
  frontend:
    volumes:
      - ./frontend:/app
      # - frontend-node-modules:/app/node_modules
    depends_on:
      - backend
    restart: unless-stopped
    build:
      context: ./frontend
    networks:
      - app-network
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    # volumes:
    # - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
