# POST http://localhost:5000/user
# POST http://185.250.44.151:5000/user
GET http://185.250.44.151:5000/hello

# content-type: application/json

# {
#     "name": "sample",
#     "email": "sam@awqe"
# }
